# Generated by Django 4.1.5 on 2023-07-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_remove_subcategory_category_remove_details_branches_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='gender',
        ),
        migrations.AlterField(
            model_name='details',
            name='age',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='details',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
