# Generated by Django 4.1.5 on 2023-07-18 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_country_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='District',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Branches',
            new_name='Subcategory',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='district',
            new_name='category',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
